input {
  beats {
    port => 5044
  }
}

filter {
  # Определяем, от какого источника пришло событие
  if [fields][log_type] == "nginx" {
    grok {
      match => { "message" => "%{IPORHOST:client_ip} - - \[%{HTTPDATE:timestamp}\] \"%{WORD:method} %{URIPATHPARAM:request} HTTP/%{NUMBER:http_version}\" %{NUMBER:response_code:int} .* \"%{GREEDYDATA:user_agent}\"" }
    }
    date {
      match => ["timestamp", "dd/MMM/yyyy:HH:mm:ss Z"]
      target => "@timestamp"
    }
    useragent {
      source => "user_agent"
      target => "user_agent_details"
    }
  }
  # В случае если ичточником будет redis
  else if [fields][log_type] == "redis" {
    grok {
      match => { "message" => "%{POSINT:pid}:%{WORD:role} %{MONTHDAY} %{MONTH} %{YEAR} %{TIME} . %{GREEDYDATA:message}" }
    }
    mutate {
      add_field => { "timestamp_str" => "%{MONTHDAY} %{MONTH} %{YEAR} %{TIME}" }
    }
    date {
      match => ["timestamp", "dd MMM yyyy HH:mm:ss.SSS"]
      target => "@timestamp"
    }
    mutate {
      gsub => [
        "level_symbol", "\\.", "debug",
        "level_symbol", "\\-", "info",
        "level_symbol", "\\*", "notice",
        "level_symbol", "\\#", "warning"
      ]
      rename => { "level_symbol" => "log_level" }
      remove_field => ["MONTHDAY", "MONTH", "YEAR", "TIME", "timestamp_str", "message"]
    }
  }
}

output {
  stdout {
  }
  elasticsearch {
      hosts => [ "${ES_HOST}" ]
      index => "logs_app_gen%-%{+YYYY.MM.dd}"
  }
}