loopback_users.guest = false
default_vhost = /
cluster_formation.peer_discovery_backend = rabbit_peer_discovery_classic_config
cluster_formation.classic_config.nodes.1 = rabbit@rabbitmq1
cluster_formation.classic_config.nodes.2 = rabbit@rabbitmq2
cluster_formation.classic_config.nodes.3 = rabbit@rabbitmq3
cluster_formation.node_cleanup.interval = 30
definitions.import_backend = local_filesystem
definitions.local.path = /etc/rabbitmq/definitions.d/
